version: '3.8'
services:
  geth_1337:
    image: ethereum/client-go
    pull_policy: always
    ports:
      - 8545:8545
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
        geth --dev --http --http.api=eth,net,web3,engine,admin --http.addr=0.0.0.0 --http.vhosts=* --http.corsdomain=*

  geth_1338:
    image: ethereum/client-go
    pull_policy: always
    ports:
      - 8546:8545
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
        geth init /root/genesis.json
        geth --networkid 1338 --http --http.api=eth,net,web3,engine,admin --http.addr=0.0.0.0 --http.port=8546 --http.vhosts=* --http.corsdomain=*
    volumes:
      - ./tests/genesis.json:/root/genesis.json
